### PR TITLE
Simplifications within if and return statements.

### PR DESCRIPTION
**Pull request by TorreyBetts**
Nothing major, just a few pieces of logic that were simplified.

### CODE REVIEW

**Comment by kcharwood** [comment]
Cherry picked change in 2.x branch with d89c4fe

**Comment by kcharwood** [comment]
Cherry picked change in 3.x branch with 6e89efe

**Comment by kcharwood** [comment]
Didn't take all of it, but I did one of them. Thanks for putting together the PR!

**Comment by TorreyBetts** [comment]
It's cool, sometimes readability trumps simplifications. Thanks!

**Pull request closed without merging**
