### PR TITLE
Added Carthage Support (iOS)

### PR DESCRIPTION
**Pull request by clsource**
Use this command in your *Cartfile* for testing.

```
github "NinjasCL/AFNetworking" "carthage"
```

then use *carthage update* for creating a iOS framework.

### CODE REVIEW

**Comment by kcharwood** [comment]
The 3.0.0 branch is fully compatible with Carthage. Thanks!

**Comment by clsource** [comment]
I needed Xcode 6.4 support for 2.x branch. Since I'm working on a legacy project that could not be updated to Xcode 7.  So this maybe usefull to someone out there :+1:

**Comment by kcharwood** [comment]
No problem! For the main project, we aren't going to backport that functionality to the 2.x branch. Glad its working in your use case.

:beers:

**Comment by BeauNouvelle** [comment]
@clsource I'd just like to thank you for putting in the time to do this. Well over a year later it's still helping people. I'm also working on some legacy code. Now I can get rid of cocoa pods and get this project in order.

**Pull request closed without merging**
