### PR TITLE
Added support for IPv6 to Reachability

### PR DESCRIPTION
**Pull request by kcharwood**
Added IPv6 support for Reachability based on the work from @SAMUKEI in #3171

### CODE REVIEW

**Comment by mkantor** [comment]
Not sure if this is the best place to ask, but I couldn't find a solid answer when googling and GitHub makes it easy to ask publicly:

Does this changeset imply that iOS apps using AFNetworking 2.x's reachability manager could incur the wrath of Apple on [2016-06-01, when IPv6-only support will be required](https://developer.apple.com/news/?id=05042016a)? Does AFNetworking 2.x work correctly in IPV6-only networks?

**Comment by sunuslee** [comment]
@mkantor 
i want this as well:)

**Comment by abournier** [comment]
Same question for me. Does AFNetworking 2.x work correctly in IPv6-only networks?

**Comment by SamehDamuni** [comment]
Same question but for AFNetworking 3.x, does it work correctly in IPv6-only networks?

**Comment by metaQ** [comment]
Same question for me.

**Comment by abournier** [comment]
I have created a NAT64 sharing internet connection as Apple recommended to test on IPv6 only, and all seems to work for my app.

**Comment by sergey-nikolaev-paycasso** [comment]
@abournier you mean the 2.x version of AFNetworking?

**Comment by abournier** [comment]
Yes, the 2.6.x.

**Comment by ryancrosby** [comment]
@abournier there also is some discussion related to this in #3496 related to AFNetworking 2.x supporting IPv6, probably better to keep discussion around version 2.x there rather than here which is focusing on 3.x.

**Comment by abournier** [comment]
Thanks for the info. I will post on the other thread.

**Comment by cezheng** [comment]
As apple has updated the [Official Reachability sample code](https://developer.apple.com/library/ios/samplecode/Reachability/Listings/Reachability_Reachability_m.html#//apple_ref/doc/uid/DTS40007324-Reachability_Reachability_m-DontLinkElementID_9), and claims that the class fully supports IPv6. But when we look at the code, it is still using `sockaddr_in` in the `reachabilityForInternetConnection` method, which makes me kind of confused.

@kcharwood However this PR actually uses ``sockaddr_in6` on iOS 9 or later. Will such implementation fail to work correctly if the device happens to be connecting to a IPv6 only network?

**Comment by hei9gag** [comment]
It seems the Reachability function is not compatible to iOS 7. The function returns not reachable status even I have connected to a IPv6 network. 

Also I found that reachabilityDidChange is slightly delay to trigger in iOS 8 (compare to iOS 9) when I try to connect to a IPv6 network from no network status. Is this a bug? Many thanks.

**Comment by kenmaz** [comment]
@cezheng 
https://forums.developer.apple.com/message/137546#137546
Apple's engineer say `0.0.0.0` address is treated as special token, it can be use for checking local connection check.Therefore `sockaddr_in` / `AF_INET` works good in IPv4 and Pv6 Network.

**Pull request merged**
