### PR TITLE
Changed SSL Pinning Error to be `NSURLErrorServerCertificateUntrusted`

### PR DESCRIPTION
**Pull request by kcharwood**
Cleaned up @0xced's work in #3169 and got the test to pass.

### CODE REVIEW

**Comment by kcharwood** [comment]
:beers:

**Comment by 0xced** [comment]
Excellent, thanks for fixing it.

Now there’s one problem remaining: the same code in the OS X Demo app returns `NSURLErrorSecureConnectionFailed` (-1200) instead of `NSURLErrorServerCertificateUntrusted`  (-1202).

Maybe we should just assert `error.code == NSURLErrorSecureConnectionFailed  || error.code == NSURLErrorServerCertificateUntrusted` in the unit test and move on?

**Comment by kcharwood** [comment]
Added the `after_failure` step back in 6831f21

**Comment by 0xced** [comment]
:+1:

**Comment by kcharwood** [comment]
I just ran the code in the OS X demo app, and got `-1202`

```
po error
Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “apple.com” which could put your confidential information at risk." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrust 0x10061a8f0 [0x7fff77785390]>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9813, NSErrorPeerCertificateChainKey=(
    "<SecCertificate 0x100619d60 [0x7fff77785390]>",
    "<SecCertificate 0x100619fa0 [0x7fff77785390]>",
    "<SecCertificate 0x10061a580 [0x7fff77785390]>"
), NSUnderlyingError=0x60000024afb0 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrust 0x10061a8f0 [0x7fff77785390]>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9813, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9813, kCFStreamPropertySSLPeerCertificates=(
    "<SecCertificate 0x100619d60 [0x7fff77785390]>",
    "<SecCertificate 0x100619fa0 [0x7fff77785390]>",
    "<SecCertificate 0x10061a580 [0x7fff77785390]>"
)}}, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “apple.com” which could put your confidential information at risk., NSErrorFailingURLKey=https://apple.com/AFNetworking/AFNetworking, NSErrorFailingURLStringKey=https://apple.com/AFNetworking/AFNetworking, NSErrorClientCertificateStateKey=0}
```

**Comment by 0xced** [comment]
Here is what I get with my [pinning-error-in-demo-app](https://github.com/0xced/AFNetworking/tree/pinning-error-in-demo-app) branch:
```
po error
Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrust 0x10071ceb0 [0x7fff74e25390]>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=(
    "<SecCertificate 0x10071c5b0 [0x7fff74e25390]>",
    "<SecCertificate 0x10071c7f0 [0x7fff74e25390]>"
), NSUnderlyingError=0x61800004e8e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrust 0x10071ceb0 [0x7fff74e25390]>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<SecCertificate 0x10071c5b0 [0x7fff74e25390]>",
    "<SecCertificate 0x10071c7f0 [0x7fff74e25390]>"
)}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://api.app.net/stream/0/posts/stream/global, NSErrorFailingURLStringKey=https://api.app.net/stream/0/posts/stream/global, NSErrorClientCertificateStateKey=0}
```

Running OS X 10.11.1 (15B42).

Can you try to run this branch and see if you get the -1200 or -1202 error?

**Comment by kcharwood** [comment]
OOOOOKKKKK...

If I add App Transport Security (Allow Arbitrary Loads) settings to the Mac Example, I get -1202. Without it, I get -1200.

**Comment by 0xced** [comment]
Of course, -1200 means an ATS issue, I should have known better! Thanks for clearing that up.

**Pull request merged**
