### PR TITLE
add retryTimes and retryFilter

### PR DESCRIPTION
**Pull request by heroims**
It's easy for us to retry..

### CODE REVIEW

**Comment by kcharwood** [comment]
I'm not sure how I feel about adding a retry mechanism to the core library. Typically, this is behavior I've seen offloaded in a subclass of your session manager. It also hasn't been an often requested feature.

Thoughts @0xced @cnoon @kylef 

Would love to hear from the rest of the community as well.

**Comment by cnoon** [comment]
I feel pretty strongly about keeping this type of behavior out of the core library. It seriously complicates things. This PR only considers data tasks, not upload or download tasks. Additionally, retry policies can essentially DDoS your servers when you have thousands or millions of users. They need to come with a progressive back off policy in order to avoid it. On-top of that, most back off policies need to be customized for each endpoint. Most of them all need to be treated differently depending on your use case.

Hence, I think it should be left out of AFN and AF core.

**Comment by kcharwood** [comment]
You did a much better job of summing up my feelings :)

Thanks for the PR, but I'm going to close this one out.

**Comment by kylef** [comment]
I agree with what @cnoon said :+1:.

**Pull request closed without merging**
