### PR TITLE
fixed memory leak on NSURLSession ("load" method in _AFURLSessionTask…

### PR DESCRIPTION
**Pull request by ferrisxie**
modified:   AFNetworking/AFURLSessionManager.m  

On xcode8, iOS10. There is a memory leak when creating a `NSURLSession` object by 
```
NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration ephemeralSessionConfiguration];
NSURLSession * session = [NSURLSession sessionWithConfiguration:configuration];
```
even if invoke the `finishTasksAndInvalidate` method.  

df9bc652-38ff-4c16-be80-af077e2d8b0b

7a407941-47f4-4830-a7a1-04f0341cd884

### CODE REVIEW

**Comment by SlaunchaMan** [comment]
Seems like a cleaner approach in general since the session isn't used for much. Can you merge in `master` so the tests pass?

**Comment by liugang1014** [comment]
I  found this memory leak too.
When to merge to pods?

**Comment by Kaspik** [comment]
Needs merge of master to fix conflicts as some of these issues have been fixed.

**Comment by jshier** [comment]
Thanks for the PR! However, due to it's age it will not be merged. If the issue is still occurring, feel free to open another PR.

**Pull request closed without merging**
