### PR TITLE
Fix #2864: allow empty x-www-form-urlencoded bodies

### LINKED ISSUE #2864: AFHTTPRequestSerializer: POSTing with no parameters results in Content-Type not being set
In `-[AFHTTPRequestSerializer requestBySerializingRequest:withParameters:error:]`, if `parameters` is `nil`, the request's `Content-Type` header is never set to `application/x-www-form-urlencoded`.

An empty string is a valid `application/x-www-form-urlencoded` POST payload.

### PR DESCRIPTION
**Pull request by jcayzac**

### CODE REVIEW

**Comment by kcharwood** [comment]
Would you be able to add tests demonstrating the fix?

**Comment by jcayzac** [comment]
@kcharwood done

**Comment by jcayzac** [comment]
@kcharwood: sorry if it sounds pushy, which is not my intent, but could you let me know what is blocking the merging of this PR (it's blocking an internal ticket we have here at my workplace, which is getting carried over to new sprints as they come in)? If it's just a lack of time, then no big deal :)

Cheers

**Comment by kcharwood** [comment]
Hey @jcayzac 

In Xcode 7, this is generating a warning:

```
/Users/kevin.harwood/GIT/AFNetworking/AFNetworking/AFURLRequestSerialization.m:533:45: Use of GNU ?: conditional expression extension, omitting middle operand
```

**Comment by jcayzac** [comment]
Hi @kcharwood!

Interesting! `?:` seems to be used in other places, but forcedly-silenced using `#pragma clang diagnostic ignored "-Wgnu"` :smile: 

Oh well, I removed it and replaced it with a good old `if`. It even makes things slightly clearer.

**Comment by kcharwood** [comment]
Sorry for the delay on getting this one.

Thanks for the PR!

:beers:

**Comment by kcharwood** [comment]
Updated in 3.0.0 with 9521690

**Pull request merged**
