### PR TITLE
Solution for issue #3619

### PR DESCRIPTION
**Pull request by funnel20**
This solves Xcode Analyzer warning for issue https://github.com/AFNetworking/AFNetworking/issues/3619

It's based on another issue https://github.com/AFNetworking/AFNetworking/issues/1675 that has a solution in another branch: https://github.com/Ner1Co/AFNetworking/commit/d11ac9618573e90b72d8c414d57d7276fe06dd0f

### CODE REVIEW

**Comment by SlaunchaMan** [comment]
Can you rebase this off of `master`?

**Comment by funnel20** [comment]
Please ignore this PR. I'm too stupid to understand Github and always fail to create proper PRs

**Comment by SlaunchaMan** [comment]
It's not your fault! The code coverage bot seems to be flagging everything.

**Comment by funnel20** [comment]
This PR is superseded by a much better solution in PR https://github.com/AFNetworking/AFNetworking/pull/4122

**Pull request closed without merging**
