### PR TITLE
prevent NSJSONSerialization from adding extra backslashes to URL strings

### PR DESCRIPTION
**Pull request by scarlettche**
By add these code ,I can prevent NSJSONSerialization from adding extra backslashes to URL strings

### CODE REVIEW

**Comment by kcharwood** [comment]
Can you please add tests demonstrating and verifying the solution?

Thanks!

**Comment by kcharwood** [comment]
@scarlettche Would you want to add some tests to this PR? Thanks!

**Comment by kcharwood** [comment]
Another bump @scarlettche. Can you show me the problem you are trying to solve. Thanks!

**Comment by kcharwood** [comment]
I'm going to close this one out for now. If you would like to revisit, please do let me know here! Thanks!

:beers:

**Comment by rodmaz** [comment]
@kcharwood This is the [problem](http://stackoverflow.com/questions/19651009/how-to-prevent-nsjsonserialization-from-adding-extra-escapes-in-url) this fix tries to solve.
iOS `NSJSONSerialization` escapes slashes and when used in HTTP body, this creates a whole lot of issues.

**Comment by kylef** [comment]
This should not be a problem though, the JSON specification states that any character may be escaped, including a forward slash.

It's common that many JSON serialises escape forward slashes for compatibility reasons.

See [RFC 7159 Section 7](https://tools.ietf.org/html/rfc7159#section-7):

> Any character may be escaped.

**Comment by rodmaz** [comment]
You are correct. I think it is an issue when (as in my case) a digest mechanism like MD5 is used in some sort of authentication mechanism. If the validation on server-side disregards the original JSON and the original escaping used (e.g. by parsing the JSON on server before the digest calculation), it may require some care on server-side.

**Pull request closed without merging**
