### PR TITLE
Implemented image downloading progress on UIImageView+AFNetworking

### PR DESCRIPTION
**Pull request by rushisangani**
**UIImageView Downloading With Progress**
Modified **UIImageView + AFNetworking** and **AFImageDownloader** to enhance
the new capability of AFNetworking by showing progress on UIImageView
while image is downloading.

### CODE REVIEW

**Comment by kcharwood** [comment]
Thanks for putting this together. Could you please add test cases? Thanks

**Comment by rushisangani** [comment]
Test cases added for AFImageDownloader and UIImageView+AFNetworking.
Also method name changed as per existing naming conventions. Thanks!

**Comment by kcharwood** [comment]
Thanks! This branch currently has a merge conflict. Could resolve that, and also clean up the white space changes so this change only represents the actual changes here?

Thanks :beers:

**Comment by kcharwood** [comment]
Also, can you create a test showing multiple callers requesting the same image URL, and both receiving the progress callback?

**Comment by rushisangani** [comment]
Thanks for pointing out this.
I've resolved the conflicts as well as added test cases for multiple caller requesting the same image URL.

I've added following test cases in **AFImageDownloaderTests.m**:

- testThatImageDownloaderDoesReportProgress
- testThatImageDownloaderDoesReportProgressForMultipleImagesSimultaneously
- testThatImageDownloaderDoesReportProgressForSimultaneouslyRequestsForTheSameAsset

and following test cases in **AFUIImageViewTests.m**

- testThatImageDoesReportDownloadProgress
- testThatImageDoesReportDownloadProgressForSameRequest

I am able to run all the test cases successfully in iOS8, iOS9.
But some how it always failed in Travis CI. (in iOS 8 only). It always got stuck in Travis CI after **testThatImageDownloaderCanDownloadImage**  this test cases.

After debugging I got the error like:  **API violation - multiple calls made to -[XCTestExpectation fulfill]** in **testThatItCanDownloadMultipleImagesSimultaneously**.

I changed this test case by declaring __weak property of XCTestExpectation and was able to run all the test case successfully. But still in Travis CI it is getting stuck after this **testThatImageDownloaderCanDownloadImage**.

Also when I run all the test cases, this **verifyReachabilityStatusBlockGetsCalledWithManager** of **AFNetworkReachabilityManagerTests.m** is getting failed sometime, but after that running it as individually, it succeeds.

Any help from your side to resolve this issues?
Thanks!

**Comment by jshier** [comment]
Thanks for the PR! However, due to its age it will not be merged. If the issue is still occurring feel free to open a new PR.

**Pull request closed without merging**
