### PR TITLE
Fix AFNetworking UIWebView extensions migrated to WKWebView

### PR DESCRIPTION
**Pull request by Tripwire999**
I've tried to remove the UIWebView references + extensions in favor of the WKWebview. Since Apple now throws warnings when submitting apps with UIWebView references (and soon will start rejecting apps using UIWebViews). I have NOT tested this myself since time constraints, also I don't really know if the Unit tests are correct with the WKNavigation object.

### CODE REVIEW

**Comment by revolter** [comment]
Duplicated of #4417.

**Comment by tjanela** [comment]
Hey everybody, #4439 is available and passing all CI tests. We have one dependency on one of our projects that uses this lib so we would like to see this addressed and a new version of AFNetworking pushed out.
Does anybody here have a direct comm channel with one of the maintainers?
Thanks!

**Comment by jshier** [comment]
Closing in favor of #4439. We'll get this released, but since it's such a breaking change we'll have to do it as a version 4. In the meantime we'll work on a 3.4 release to fix as many bugs as possible and then move to the more breaking changes.

**Comment by davide1945** [comment]
Hi @jshier, I've encountered this problem and my app can't be published until the release of the version 4, the one without UIWebView.
Do you have an estimated date for the release of this breaking change version? Or can I use some workaround to get my app publishable again? 

My problem is that I need to use the methods contained in the `UIKit` subspec, in particular the ones contained here `#import <AFNetworking/UIImageView+AFNetworking.h>` and here `#import <AFNetworking/AFImageDownloader.h>`.

Thank you in advance for your time and your patience.
Have a nice day,
Davide

**Comment by martinprot** [comment]
I confirm UIWebView is still part of AFNetworking 3.2.1

@davide1945 a quick and temporary workaround is to edit the AFNetworking pod :
- remove `UIWebView+AFNetworking.h/.m` from the lib (you can uncheck them from the target membership panel
- go to `UIKit+AFNetworking.h` and comment `#import "UIWebView+AFNetworking.h"`
- go to `AFNetworking-umbrella.h` and comment `#import "UIWebView+AFNetworking.h"`

Note that this is a temporary workaround, and you will do it again each time you `pod update`.

**Comment by harrisrap** [comment]
@jshier Any updates on this? April is coming quick, and we need to get this fix in our apps ASAP. Can you at least give us an estimate on when you think it will be available? Thanks.

**Pull request closed without merging**
