### PR TITLE
Allow return value of HTTP redirection block to be NULL

### PR DESCRIPTION
**Pull request by TheDom**
This addresses https://github.com/AFNetworking/AFNetworking/issues/3974

### CODE REVIEW

**Comment by SlaunchaMan** [comment]
Thanks for the PR! Can you merge in `master` or rebase so that the tests pass?

**Comment by TheDom** [comment]
Done! :)

**Comment by SlaunchaMan** [comment]
@jshier This should be good to merge!

**Comment by jshier** [comment]
@SlaunchaMan Any idea why the diff is showing cert changes? Otherwise it looks good.

**Comment by SlaunchaMan** [comment]
I’m pretty sure that’s just from `master` being merged in. Feel free to cherry-pick and close if that’s cleaner.

**Pull request merged**
