### PR TITLE
Fixed image memory calculation

### PR DESCRIPTION
**Pull request by SummertimSadness**
Fixed image memory calculation

### CODE REVIEW

**Comment by SummertimSadness** [comment]
Fixed image memory calculation

**Comment by cnoon** [comment]
This logic is exactly the same @SummertimSadness. Your calculation just multiplies `width` x `height` and then by `bytesPerPixel` instead of the row size which is `width` x `bytesPerPixel` then finally by the `height`. Both operations result in the same value. 

I'm going to close this PR out for now. If I'm missing something very obvious, please point out my mistake and I'll gladly re-open.

Cheers. 🍻

**Comment by tewha** [comment]
Ack. Take another look.

        CGFloat bytesPerRow = imageSize.width * bytesPerPixel;
        self.totalBytes = (UInt64)bytesPerPixel * (UInt64)bytesPerRow;

Where's `imageSize.height`?

**Comment by cnoon** [comment]
Doh, sometimes you look at something way too many times. Thanks @tewha!

**Comment by kcharwood** [comment]
Thanks for merging this in @cnoon!

Do you recall if there were issues with tests here? I think I recall the original PR failing tests.

**Comment by cnoon** [comment]
Hmmmm...let me take a look. Travis has been so messed up over the past two weeks on AF that I've stopped paying attention.

**Comment by SummertimSadness** [comment]
我感觉totalBytes的计算方式不是最好的，而且dispatch_barrier_async的性能很低，我会继续优化这部分代码，非常高兴能为AF贡献

**Pull request merged**
