### PR TITLE
Fixes #3271, Progress blocks not called on main thread

### LINKED ISSUE #3271: Progress blocks not called on main thread
Similar to issue #411 for the operation based APIs, the progress blocks for the session APIs aren't being called on the main thread.

For session based APIs, the KVO observation callbacks are happening on Apple's work queue (eg `com.apple.NSURLSession-work`), so that is the queue the upload and download progress blocks are being called on.

Instead, it would be good to have these calls happen on the same work queue and group as the completion callbacks. This would be in line with the operation based APIs.

I discovered this problem when refactoring a codebase to use the new API, and hit a threading problem when calling into UIKit from a background queue. I suspect others will encounter this as they move to the session based API.

### PR DESCRIPTION
**Pull request by wooster**

### CODE REVIEW

**Comment by kcharwood** [comment]
Thanks for the PR!

This is a tricky part to the NSProgress API.

Check out my reasoning in #3187 for why this is the case. It's also called out in the documentation for all of those methods. Basically, if you dispatch out to the main queue, and pass the NSProgress reference, the reference may be updated again before it runs on the main queue, leading to confusion and the appearance of nothing being updated.

By returning it on the session queue, I leave flexibility in to allow the caller to get every update, and then determine what to do with it (in the case it needs to be vended to the main queue for UI updates).

I'm open to hearing feedback from the community, but that's where I've landed so far.

**Comment by wooster** [comment]
@kcharwood: I'm not a big fan of leaving land mines like this in API.

Two alternatives:

* Un-deprecate the methods without the progress blocks. As it stands, we've now got potential threading problems all over our code base, waiting to be misused.
* Construct new NSProgress objects for each update, and send those across the completion queue.

**Comment by kcharwood** [comment]
It's something I've _really_ struggled with. I don't think creating new NSProgress objects is the best option for how NSProgress is designed (give the use of child progresses and things like that).

I would say the options are:

1) Keep it as is, and instruct through documentation and proper naming.
2) Convert the block to use primitive objects, and simply pass them back and let the caller do the math (`bytesReceived`, `expectedBytesReceived`, etc)

The first option gives us the ability to leverage the power of NSProgress (still an underused object in the iOS SDK), while forcing us to manage main queue dispatching ourselves. The second forces us to lose the power of NSProgress, but get a better expected callback.

Note that NSURLSession does call you back on the session queue for those updates, so its a pattern that does follow how NSURLSession works.

Unfortunately I'm left with two options that I don't 100% like :(

**Comment by wooster** [comment]
My vote would be to un-deprecate the API that doesn't include the progress block parameters.

I'll keep looking for another solution, though, because having this kind of land mine in large projects isn't ideal.

**Comment by kcharwood** [comment]
I'll do some more thinking on this front. I view it as a "less" of a land mine because its the same behavior NSURLSession would give you if you were use it directly. I agree its not optimal though.

**Pull request closed without merging**
