### PR TITLE
Added some casts to fix compiler errors with strict build settings. R…

### PR DESCRIPTION
**Pull request by born2pun**
…enamed some function parameters to avoid reserved keyword issues if the compiler is set for Obj-C++.

### CODE REVIEW

**Comment by kcharwood** [comment]
Which build settings are you using here?

**Comment by born2pun** [comment]
I have build settings in a .xcconfig file. Here are the compiler-specific ones I've set, which are overriding Xcode's defaults.

CLANG_ANALYZER_SECURITY_FLOATLOOPCOUNTER	= YES
CLANG_ANALYZER_SECURITY_INSECUREAPI_RAND	= YES
CLANG_ANALYZER_SECURITY_INSECUREAPI_STRCPY	= YES
CLANG_CXX_LANGUAGE_STANDARD			= gnu++0x
CLANG_CXX_LIBRARY				= libc++
CLANG_ENABLE_MODULES				= YES
CLANG_ENABLE_OBJC_ARC				= YES
CLANG_WARN_BOOL_CONVERSION			= YES
CLANG_WARN_CONSTANT_CONVERSION			= YES
CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS	= YES
CLANG_WARN_DIRECT_OBJC_ISA_USAGE		= YES_ERROR
CLANG_WARN_EMPTY_BODY				= YES
CLANG_WARN_ENUM_CONVERSION			= YES
CLANG_WARN_IMPLICIT_SIGN_CONVERSION		= YES
CLANG_WARN_INT_CONVERSION			= YES
CLANG_WARN_OBJC_EXPLICIT_OWNERSHIP_TYPE		= YES
CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF		= YES
CLANG_WARN_OBJC_MISSING_PROPERTY_SYNTHESIS	= YES
CLANG_WARN_OBJC_RECEIVER_WEAK			= YES
CLANG_WARN_OBJC_REPEATED_USE_OF_WEAK		= YES
CLANG_WARN_OBJC_ROOT_CLASS			= YES_ERROR
CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION	= YES
CLANG_WARN__DUPLICATE_METHOD_MATCH		= YES
GCC_C_LANGUAGE_STANDARD				= gnu99
GCC_DEBUGGING_SYMBOLS				= full
GCC_ENABLE_CPP_EXCEPTIONS			= YES
GCC_ENABLE_CPP_RTTI				= NO
GCC_INPUT_FILETYPE				= sourcecode.cpp.objcpp
GCC_WARN_ABOUT_MISSING_FIELD_INITIALIZERS	= YES
GCC_WARN_ABOUT_MISSING_NEWLINE			= YES
GCC_WARN_ABOUT_MISSING_PROTOTYPES		= YES
GCC_WARN_ABOUT_RETURN_TYPE			= YES_ERROR
GCC_WARN_INITIALIZER_NOT_FULLY_BRACKETED	= YES
GCC_WARN_MULTIPLE_DEFINITION_TYPES_FOR_SELECTOR	= YES
GCC_WARN_SHADOW					= YES
GCC_WARN_SIGN_COMPARE				= YES
GCC_WARN_UNDECLARED_SELECTOR			= YES
GCC_WARN_UNINITIALIZED_AUTOS			= YES
GCC_WARN_UNKNOWN_PRAGMAS			= YES
GCC_WARN_UNUSED_FUNCTION			= YES
GCC_WARN_UNUSED_LABEL				= YES
GCC_WARN_UNUSED_PARAMETER			= YES
GCC_WARN_UNUSED_VARIABLE			= YES

**Comment by kcharwood** [comment]
@born2pun Would you be able to rebase this branch? Currently it has a conflict with master.

Thanks!

**Comment by kcharwood** [comment]
I've taken your changes, along with a few other clean ups here: https://github.com/AFNetworking/AFNetworking/tree/3019

Will be making a PR soon.

**Pull request closed without merging**
