### PR TITLE
Changed Accept-Language header to start with the locale with country code

### PR DESCRIPTION
**Pull request by patcheng**
[NSLocale preferredLanguages] returns a list of 'primary-tag', e.g. en, fr, zh-Hans

That is not ideal when the server needs to know the country code of those locale.

So, prepend the header with a more explicit locale constructed from [NSLocale currentLocale]

### CODE REVIEW

**Comment by kcharwood** [comment]
Locale code. It's amazing how convoluted this is on iOS. And neither of these approaches show the actual language the app is being presented in! You have to go to NSBundle mainBundle for that.

This is certainly important to get right, but I want to make sure we are getting it right here.

**Comment by kcharwood** [comment]
Would you be able to add some tests here?

**Comment by patcheng** [comment]
I re-did the change in https://github.com/AFNetworking/AFNetworking/issues/2888 (hopefully it's easier to follow)

**Comment by kcharwood** [comment]
closing this for #2888

**Pull request closed without merging**
