### PR TITLE
Fix carthage support 2.x

### PR DESCRIPTION
**Pull request by dulaccc**
Hey,

Because our app is heavily based on `NSOperation` usage, we are not able to upgrade to `3.0` for now. But the project wasn't compatible with Carthage, so I made this little fix (inspired by the compatibility work made on the 3.0 version)

Cheers

### CODE REVIEW

**Comment by kaweepong2521** [comment]
good

**Comment by kaweepong2521** [comment]
namdet k.

**Comment by kaweepong2521** [comment]
You’re receiving notifications because you commented.namdet k.

**Comment by kcharwood** [comment]
Thanks @dulaccc. However at this point, we are only taking critical security patches for 2.x.

The great thing about Carthage is you can just point it at your branch in your Cartfile, rather than `AFNetworking/AFNetworking`. For now, anyone looking for Carthage support for that version can look there.

:beers:

**Pull request closed without merging**
