### PR TITLE
Feature Request: Support GIFs

### PR DESCRIPTION
**Pull request by RbBtSn0w**
That's was support GIFs feature for AFNetworking.

### CODE REVIEW

**Comment by kcharwood** [comment]
Can you add some tests to this? Thanks!

**Comment by kcharwood** [comment]
@RbBtSn0w Would you be able to rebase this and add some tests?

**Comment by RbBtSn0w** [comment]
@kcharwood had tests. 💯

**Comment by RbBtSn0w** [comment]
Close this request.

Rebase and testing at #3772

Feature Request: Support GIFs #3772

https://github.com/AFNetworking/AFNetworking/pull/3772

**Pull request closed without merging**
