### PR TITLE
AFURLSessionManager Background upload Tests

### PR DESCRIPTION
**Pull request by LinkedHK**
Added a test case as requested in the issue  
https://github.com/AFNetworking/AFNetworking/issues/3203#issuecomment-164001494

### CODE REVIEW

**Comment by kcharwood** [comment]
Thanks! I'll dig into this later today.

**Comment by LinkedHK** [comment]
The build fails .. For some reason header file <XCTest/XCTest.h> cannot be found :(

**Comment by kcharwood** [comment]
You need to add the test file to the test target, and remove it from the AFNetworking iOS Framework.

**Comment by LinkedHK** [comment]
Ok. I will fix it in a moment

**Comment by kcharwood** [comment]
There are some issues with your test setup. I think you were shooting for this:

```
    NSString *uploadUrl = [NSString stringWithFormat:@"%@%@",AFNetworkingTestsBaseURLString,@"post"];
    NSString *imageURL = [NSString stringWithFormat:@"%@%@",AFNetworkingTestsBaseURLString,@"image/jpeg"];
    NSData * fileData =  [NSData dataWithContentsOfURL:[NSURL URLWithString:imageURL]];
```

**Comment by LinkedHK** [comment]
Indeed. I didn't notice that  Xcode  removed a slash :(

**Comment by LinkedHK** [comment]
Thank you for pointing out . Fixed!

**Comment by kcharwood** [comment]
From the [URL Session Docs](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/URLLoadingSystem/Articles/UsingNSURLSession.html) in regard to Background Transfer Considerations:

> Only upload tasks from a file are supported (uploading from data objects or a stream will fail after the program exits).

**Comment by kcharwood** [comment]
I think you want to use:

```
- (NSURLSessionUploadTask *)uploadTaskWithRequest:(NSURLRequest *)request
                                         fromFile:(NSURL *)fileURL
                                         progress:(nullable void (^)(NSProgress *uploadProgress)) uploadProgressBlock
                                completionHandler:(nullable void (^)(NSURLResponse *response, id _Nullable responseObject, NSError  * _Nullable error))completionHandler;
```

**Comment by LinkedHK** [comment]
@kcharwood  It's right,. I will remove this test.  but there is the second  test which uses uploadTaskWithRequest and It fails. because for some reason no parameters are submitted. :(

**Comment by LinkedHK** [comment]
@kcharwood 
Hi. I wasted so much time figuring out that the upload parameters should be appended to the file. No clear mention about it neither in docs / the examples of  AFNetworking.. So the method
```
- (NSMutableURLRequest *)requestWithMultipartFormRequest:(NSURLRequest *)request
                             writingStreamContentsToFile:(NSURL *)fileURL
                                       completionHandler:(void (^)(NSError *error))handler
```
Should be used here.

**Comment by hzh137940556** [comment]
hi,I met the same problem，i want to upload muiltabel files,  what can i do  ? i  use  (uploadTaskWithRequest:(NSURLRequest *)request
                                         fromFile:(NSURL *)fileURL
                                         progress:(nullable void (^)(NSProgress *uploadProgress)) uploadProgressBlock
                                completionHandler:(nullable void (^)(NSURLResponse *response, id _Nullable responseObject, NSError  * _Nullable error))completionHandler;) 
 but it only upload one file. For example, I want to upload more than one video

**Comment by hzh137940556** [comment]
@LinkedHK 
@kcharwood
 hi,I met the same problem，i want to upload muiltabel files,  what can i do  ? i  use  (uploadTaskWithRequest:(NSURLRequest *)request
                                         fromFile:(NSURL *)fileURL
                                         progress:(nullable void (^)(NSProgress *uploadProgress)) uploadProgressBlock
                                completionHandler:(nullable void (^)(NSURLResponse *response, id _Nullable responseObject, NSError  * _Nullable error))completionHandler;) 
 but it only upload one file. For example, I want to upload more than one video

**Comment by jshier** [comment]
Thanks for the PR! However, due to its age it will not be merged. If the issue is still occurring feel free to open a new PR.

**Pull request closed without merging**
