### PR TITLE
Add nullability specifiers to all 'id responseObject' parameters

### PR DESCRIPTION
**Pull request by sashaweiss**
This PR is a follow-up to the discussion + PR happening at #4296, and building/running/adding tests appears to be dependent on #4329.

These changes add `__nullable` specifiers to each location `id responseObject` appears in a method or closure signature, which should alleviate the Swift-Objc interop issues identified in the first PR referenced above.

I'm relatively new to Objc (mostly work in Swift), so please let me know if this is overkill or misses something big - tried to make the smallest number of changes I could while covering everything.

Once the Podfile update PR goes through I'll rebase to get those changes, make sure the existing tests pass, etc. I wasn't sure the best way to add tests for these changes, since they don't change any logic and are instead compiler-related...I could add some basic request tests made in Swift, potentially? But I'm not sure how one would gracefully fail the test if the changes _don't_ work, since they currently just result in an unhandleable crash.

Opening this now so that once the above PRs are done, this will hopefully be ready shortly thereafter. Looking forward to hearing your thoughts. Thanks!

### CODE REVIEW

**Comment by sashaweiss** [comment]
Hey all, just wanted to check in post-holidays and see if anyone might be available to take a look at this?

Thanks so much!

**Comment by sashaweiss** [comment]
Hey all, just wanted to check in post-holidays and see if anyone might be available to take a look at this?

Thanks so much!

**Comment by Malkavian89** [comment]
this fixes a very nasty bug. thank you.

**Comment by SlaunchaMan** [comment]
Can you merge in the latest changes from the `2.x` branch? Tests are now passing on CI!

**Comment by sashaweiss** [comment]
@SlaunchaMan just did (still novice working with multiple remotes, but I think it went correctly?).

Fingers crossed for Travis!

**Comment by sashaweiss** [comment]
Also, thanks for taking this back up! Got sidetracked over the holidays and this ended up pretty far down my backlog.

**Comment by sashaweiss** [comment]
🎉 Tests are indeed passing on CI!

**Comment by sashaweiss** [comment]
Thanks for the merge, @SlaunchaMan.

Should I just keep an eye out for a 2.7 release, or are there other things I can do to help?

**Comment by SlaunchaMan** [comment]
Thanks, this is released now!

**Pull request merged**
