### PR TITLE
Fix travis CI build

### PR DESCRIPTION
**Pull request by bofeizhu**
Remove outdated envs. Unblock #4439.

### CODE REVIEW

**Comment by bofeizhu** [comment]
@jshier `✗ testProgressIsSet, Asynchronous wait failed: Exceeded timeout of 20 seconds, with unfulfilled expectations: "Expect value of 'fractionCompleted' of <NSProgress: 0x60e000076e80> : Parent: 0x0 (portion: 0) / Fraction completed: 0.0000 / Completed: 0 of -1   to be '1'".` This test failed randomly. Should we remove it?

**Comment by bofeizhu** [comment]
I added Xcode 11 and remove both Xcode 8 & 7. Lmk if you think I should add Xcode 8 back.

**Comment by bofeizhu** [comment]
@jshier I got all the CI passing. Could we merge this?

**Comment by kinarobin** [comment]
LGTM！

**Comment by hotbott** [comment]
Also fixes Carthage compilation issues on Xcode 11.

**Comment by hotbott** [comment]
Any plans to merge that PR soon? As mentioned, the framework is not working with *Carthage* right now!

**Comment by bofeizhu** [comment]
@hotbott Unfortunately, I'm not the maintainer for this repo 😞. I can't merge this PR by myself.

**Comment by hotbott** [comment]
@jehier Please review && release

**Comment by tmm1** [comment]
Ping

**Comment by bofeizhu** [comment]
@jshier https://developer.apple.com/news/?id=12232019b

**Comment by jshier** [comment]
@bofeizhu Good work here! However, we can't yet drop testing support for older OS versions, so we need to bring the older versions back. I believe AFNetworking still technically supports back to Xcode 7, but I think Xcode 8.3 is as far back as we need to go right now. We don't need a huge amount of device coverage, just one per version / platform should be enough. So the following Travis images can be used:

- `xcode11.3`
- `xcode10.3`
- `xcode9.4`
- `xcode8.3`

If the 8.3 or 9.4 environments are too old to support the Ruby environment we need, that's fine, we can do without, but I'd like to make sure.

Finally, feel free to remove that `UIWebView` test that was commented out.

**Comment by jshier** [comment]
@bofeizhu Actually, I'm going to merge this as is to get Travis working. But I'd appreciate an additional PR that adds the older versions back.

**Comment by bofeizhu** [comment]
@jshier Sure, I can submit an additional PR next week. Thank you!

**Pull request merged**
