### PR TITLE
add missing __nullable attributes

### PR DESCRIPTION
**Pull request by hoppenichu**
as titled

### CODE REVIEW

**Comment by kcharwood** [comment]
Hi @hoppenichu. Under what conditions do you see those come back as nil? I'd like to add tests if possible, and make sure the documentation is up to date.

**Comment by hoppenichu** [comment]
In case request serialization error occurred.

**Comment by kcharwood** [comment]
Ah you're right! I totally missed that looking over that code. I'll get this patch in!

Thanks :beers:

**Comment by kcharwood** [comment]
Added unit test and merged in 2.x with c90c3da

**Comment by kcharwood** [comment]
Merged in 3.0.0 with 9200627

**Comment by kcharwood** [comment]
:beers:

**Comment by hoppenichu** [comment]
:+1:

**Pull request closed without merging**
