### PR TITLE
Add FOUNDATION_EXPORT for AFJSONObjectByRemovingKeysWithNullValues

### PR DESCRIPTION
**Pull request by ElfSundae**

### CODE REVIEW

**Comment by jshier** [comment]
Why is this necessary?

**Comment by ElfSundae** [comment]
Just like any other C declarations in header files,  adding `FOUNDATION_EXPORT` to export C/ObjC constants/functions to ObjC++, ie `.mm` files.
```objc
#if defined(__cplusplus)
#define FOUNDATION_EXTERN extern "C"
#else
#define FOUNDATION_EXTERN extern
#endif

#define FOUNDATION_EXPORT FOUNDATION_EXTERN
```
You may use `AFJSONObjectByRemovingKeysWithNullValues` in any `.mm` file to see what will happen.

**Comment by jshier** [comment]
Ah, I see it's commonly used to expose constants and functions. I'll merge this PR but if you want to do a full audit to see if there are any other issues I'd appreciate it.

**Comment by ElfSundae** [comment]
I have checked others before this PR, only this one, newly exposed.

**Comment by jshier** [comment]
Great, thanks! 👍

**Pull request merged**
