### PR TITLE
Fix certificate validation for servers providing incomplete chains

### PR DESCRIPTION
**Pull request by p4checo**
Some servers send incomplete certificate chains (without the Root CA), which cause issues in the latest version's (2.6.0) certificate pinning mechanism. In these cases, when `AFSecurityPolicy`s `-evaluateServerTrust:` invokes `AFCertificateTrustChainForServerTrust(serverTrust)` (prior to setting the
anchor), the Root CA isn't present (the server didn't send it).

Afterwards, even though `AFServerTrustIsValid(serverTrust)` succeeds, the next validation fails since no pinned certificate matches any of the `serverCertificates`.

By fetching the `AFCertificateTrustChainForServerTrust(serverTrust)` *after* the `AFServerTrustIsValid(serverTrust)` validation, the complete chain is obtained and the Root CAs match (pinned vs validated).

A slight optimization was also made when validating if the `serverTrust` certificates contain the `pinnedCertificates`, looping in reverse order and returning after finding the first match.

I've included a new test that demonstrates the mentioned issue is fixed by this patch.

### CODE REVIEW

**Comment by mthole** [comment]
I ran into this issue today after updating AFNetworking. I've verified that @p4checo's fix brings back the expected behavior. Thank's @p4checo!

Please take in a timely manner. :bow:

**Comment by p4checo** [comment]
Cheers @mthole! :smile:

**Comment by p4checo** [comment]
I realized that the Root CA certificate is always in the last position of the `serverCertificates`, and since the Root CA's are the ones that should be pinned, it makes sense to loop the array in the reverse order.

**Comment by mthole** [comment]
Ping. Could you take a look at this one?

**Comment by kcharwood** [comment]
Are there any public endpoints that you are aware of that exhibit this behavior? I'd like to dig in and walk through it myself before pulling it in.

Thanks!

**Comment by rafaelc0sta** [comment]
@kcharwood I believe this behaviour is the one originally expected in AFSSLPinningModeCertificate, but as it wasn't being done, I made AFSSLPinningModeCA in https://github.com/AFNetworking/AFNetworking/pull/3136

**Comment by p4checo** [comment]
@kcharwood, I've found a public endpoint which exhibits this behavior -> *google.com* :smile: 

It appears google.com doesn't send the complete chain, because it assumes it's Root CA's are already in everyone else's trust stores (you can verify this [here](https://www.ssllabs.com/ssltest/analyze.html?d=google.com), in the Certification Paths section). 

However, when pinning we should pin precisely the Root CA's to avoid MiTM attacks, and if we do that in 2.6.0 the requests fail, as the test code below will show. When tested using my branch, the request succeeds.

Here's the code you can use to test:
```
    NSString *googleEquifaxRootCAString =
        @"MIIDIDCCAomgAwIBAgIENd70zzANBgkqhkiG9w0BAQUFADBOMQswCQYDVQQGEwJV"
        @"UzEQMA4GA1UEChMHRXF1aWZheDEtMCsGA1UECxMkRXF1aWZheCBTZWN1cmUgQ2Vy"
        @"dGlmaWNhdGUgQXV0aG9yaXR5MB4XDTk4MDgyMjE2NDE1MVoXDTE4MDgyMjE2NDE1"
        @"MVowTjELMAkGA1UEBhMCVVMxEDAOBgNVBAoTB0VxdWlmYXgxLTArBgNVBAsTJEVx"
        @"dWlmYXggU2VjdXJlIENlcnRpZmljYXRlIEF1dGhvcml0eTCBnzANBgkqhkiG9w0B"
        @"AQEFAAOBjQAwgYkCgYEAwV2xWGcIYu6gmi0fCG2RFGiYCh7+2gRvE4RiIcPRfM6f"
        @"BeC4AfBONOziipUEZKzxa1NfBbPLZ4C/QgKO/t0BCezhABRP/PvwDN1Dulsr4R+A"
        @"cJkVV5MW8Q+XarfCaCMczE1ZMKxRHjuvK9buY0V7xdlfUNLjUA86iOe/FP3gx7kC"
        @"AwEAAaOCAQkwggEFMHAGA1UdHwRpMGcwZaBjoGGkXzBdMQswCQYDVQQGEwJVUzEQ"
        @"MA4GA1UEChMHRXF1aWZheDEtMCsGA1UECxMkRXF1aWZheCBTZWN1cmUgQ2VydGlm"
        @"aWNhdGUgQXV0aG9yaXR5MQ0wCwYDVQQDEwRDUkwxMBoGA1UdEAQTMBGBDzIwMTgw"
        @"ODIyMTY0MTUxWjALBgNVHQ8EBAMCAQYwHwYDVR0jBBgwFoAUSOZo+SvSspXXR9gj"
        @"IBBPM5iQn9QwHQYDVR0OBBYEFEjmaPkr0rKV10fYIyAQTzOYkJ/UMAwGA1UdEwQF"
        @"MAMBAf8wGgYJKoZIhvZ9B0EABA0wCxsFVjMuMGMDAgbAMA0GCSqGSIb3DQEBBQUA"
        @"A4GBAFjOKer89961zgK5F7WF0bnj4JXMJTENAKaSbn+2kmOeUJXRmm/kEd5jhW6Y"
        @"7qj/WsjTVbJmcVfewCHrPSqnI0kBBIZCe/zuf6IWUrVnZ9NA2zsmWLIodz2uFHdh"
        @"1voqZiegDfqnc1zqcPGUIWVEX/r87yloqaKHee9570+sB3c4";

    NSData *googleEquifaxRootCAData =
        [[NSData alloc] initWithBase64EncodedString:googleEquifaxRootCAString
                                            options:NSDataBase64DecodingIgnoreUnknownCharacters];

    AFSecurityPolicy *policy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeCertificate];
    policy.pinnedCertificates = @[ googleEquifaxRootCAData ];

    NSURL *url = [NSURL URLWithString:@"https://google.com"];

    AFHTTPSessionManager *sessionManager = [[AFHTTPSessionManager alloc] initWithBaseURL:url];
    sessionManager.securityPolicy = policy;
    sessionManager.responseSerializer = [[AFHTTPResponseSerializer alloc] init];

    [sessionManager GET:@""
        parameters:nil
        success:^(__unused NSURLSessionDataTask *_Nonnull task, id _Nonnull responseObject) {
            NSLog(@"HTML:\n %@", [[NSString alloc] initWithData:responseObject encoding:NSASCIIStringEncoding]);
        }
        failure:^(__unused NSURLSessionDataTask *_Nonnull task, NSError *_Nonnull error) {
            NSLog(@"Error: %@", error);
        }];
```

Let me know if you need anything else :wink:

**Comment by kcharwood** [comment]
Thanks for the write up! I'm looking into it now.

I may ask you to retarget this at the 3_0_0_branch.

**Comment by p4checo** [comment]
Ok, no problem.

**Comment by kcharwood** [comment]
I think the certs included for tests have expired! Would you be be able to update that and retarget it for the 3.0.0 branch?

**Comment by p4checo** [comment]
You're right! I'll update it and create a new PR pointing to the 3.0.0 branch

**Comment by kcharwood** [comment]
:beers:

**Pull request closed without merging**
