### PR TITLE
Make sure NSNotificationCenter interactions take place in their own queue

### LINKED ISSUE #2439: AFNetworkActivityIndicatorManager taskDidResume erratic crash
Hi Matt!

Firstly, many thanks for your hard work in AFN and I've done my best to make sure the issue isn't on my end!

I'm using a UIRefreshControl in a UITableViewController similar to how GlobalTimelineViewController uses one in the AFNetworking example.  However, after 3-5 table refreshes, I'm getting a unrecognized selector crash when AFURLSessionManager's  `taskDidResume:` (AFURLSessionManager.m:402) is trying to send a `AFNetworkingTaskDidResumeNotification` to `networkRequestDidStart:` of an instance of AFNetworkActivityIndicatorManager.  

This issue occurred in rev 29511 and still occurs in the latest  29542, so this is not newly introduced.

Separately, I wanted to point out that the property `refreshControl` is redundant in GlobalTimelineViewController.m:34 since it's also available in UITableViewController.

Thanks,
Drew

### PR DESCRIPTION
**Pull request by sergiou87**
This should fix #2439 

If I'm right, the problem was this:
 1. Thread A: `- [NSURLSessionDataTask resume]` is called. The swizzled method `af_resume` posts a `AFNSURLSessionTaskDidResumeNotification` notification. The callback for that notification is not invoked (yet).
 2. Thread B: an instance of `AFHTTPSessionManager` is deallocated. That means, it removes itself as observer of `AFNSURLSessionTaskDidResumeNotification` (but now it's too late!).
 3. Thread A: the callback of `AFNSURLSessionTaskDidResumeNotification` is invoked (`-[AFURLSessionManager taskDidResume:]`) in the instance deallocated in thread B (step 2) and tries to access a property of it.
 4. CRASH!!!

You can reproduce it with the following code in your AppDelegate (you may need to run it several times, and each time you will get different crashes depending on when it switches between threads). This doesn't happen if you built the app with iOS 9 SDK and running on iOS 9, because of the changes Apple introduced on `NSNotificationCenter`, but it definitely happens on iOS 8 (no matter what SDK you used) and iOS 9 if the app was built with iOS 8 SDK.

The numbers for the iterations (and even part of the code) is kind of random, I just wanted to copy the exact code that reproduced the problem. It just creates a bunch of `AFHTTPSessionManager` with short life-span, and concurrently creates tasks and resumes them.

```objective-c
#import "AFNetworking.h"

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    AFHTTPSessionManager *sm = [[AFHTTPSessionManager alloc] initWithBaseURL:[NSURL URLWithString:@"http://127.0.0.1:8080"]];

    for (NSUInteger k=0; k < 20; k++)
    {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{
            for (NSUInteger i=0; i < 100; i++)
            {
                NSURLSessionDataTask *task = [sm dataTaskWithRequest:[NSURLRequest requestWithURL:[NSURL URLWithString:@"http://127.0.0.1:8080"]] completionHandler:nil];
                [task resume];

            }
        });

        for (NSUInteger i=0; i < 100; i++)
        {
            @autoreleasepool {
                AFHTTPSessionManager *j = [[AFHTTPSessionManager alloc] initWithBaseURL:[NSURL URLWithString:@"http://127.0.0.1:8080"]];

                [j invalidateSessionCancelingTasks:YES];
            }
        }
    }

    return YES;
}
```

### CODE REVIEW

**Comment by sergiou87** [comment]
I made some changes and broke the tests, I'll fixe them ASAP.

**Comment by kcharwood** [comment]
It is possible to write a unit test displaying this behavior?

**Comment by sergiou87** [comment]
I can't think of a deterministic way to reproduce this: you need to post the notification in one thread, and right after that and before it finishes executing the callback, the `AFURLSessionManager` instance must be deallocated. That's why my sample code creates lots of instances (that are almost immediately deallocated) and posts lots of notifications concurrently, and even that is not 100% reliable (although for me it crashed most of the times I ran it).

Anyway, I'm open to suggestions :sweat_smile:

**Comment by kcharwood** [comment]
@sergiou87 What version of Xcode and iOS were you reproducing this on? Trying now.

**Comment by kcharwood** [comment]
This is definitely reproducible in the app delegate. I can get a test target to crash though.

**Comment by kcharwood** [comment]
I'm also having trouble getting the AFURLSessionManagerTests to pass locally. Are you using any issues there?

**Comment by sergiou87** [comment]
Hey! @kcharwood : we get thousands of those crashes in a released app :disappointed: 

Regarding the tests, all the asynchronous tests weren't needed because the suspend/resume notifications were posted synchronously. Now all tests run in parallel sharing the same sync queue for those notifications (`url_session_manager_notification_queue`), so they block each other and that makes the tests time out. If you increase the test timeouts to a high value (10 was enough on my laptop) it works, but of course that's not the best way to fix it…

We should be somehow able to inject different queues for each test so they continue being independent while on release they all keep the same queue, but I hadn't time to work on that, sorry :confused: 

And again, I'm open to suggestions :stuck_out_tongue_winking_eye:

**Comment by kcharwood** [comment]
I wonder if this could be filtered down a different way? Maybe only adding the notification observer for the specific tasks a session creates? Then it wouldn't get notified from tasks on other sessions?

**Comment by kcharwood** [comment]
@sergiou87 what do you think about 8370ccb? All tests pass with that patch. Can you see if that makes a difference in your code base?

Thoughts from @cnoon @kylef @jshier ?

I'm assuming `object` on `NSNotificationCenter addObserver:selector:name:object` is a weakly held reference and I don't need to explicitly unregister it, but I can't find documentation backing that up.

**Comment by jshier** [comment]
Unless you're running on iOS 9 only, `NSNotificationCenter` observers need to be explicitly removed using `removeObserver:`.

**Comment by kcharwood** [comment]
Hey @jshier. Not the observer, but the object.

**Comment by jshier** [comment]
Sorry, missed that part.

For the purposes of memory management that's correct, AFAICT. However, the `NSNotificationCenter` docs do state that `removeObserver:` should be called before `object:` is deallocated. I'm not sure that possible in the alternate solution.

**Comment by kcharwood** [comment]
If that's the case, we would need to remove the observer in the completion blocks for all the tasks.

**Comment by sergiou87** [comment]
@kcharwood Sorry I've been too busy these days… the problem with that alternate solution is that it doesn't solve the problem, it just makes it less probable (because the session manager doesn't listen to EVERY task in the app anymore), but it still can happen that the session manager gets deallocated right after a task posted a notification and before it's handled.

So you're patch doesn't fix the problem, but I'd keep it because IMHO it's a great addition.

**Comment by sergiou87** [comment]
@kcharwood  Actually, maybe with that change you made we can switch to one notification queue per session manager, instead of having one shared which would make the tests independent again.

**Comment by kcharwood** [comment]
@sergiou87 It may actually fix it though. Is it possible for a session to be dealloc'ed if existing tasks associated with it are still in flight? If thats not possible, then this just might solve it. I need to look into some the cancel state today and verify those flows.

**Comment by kcharwood** [comment]
I made some additional updates in 69f7ca0 to manage adding/removing observers.

**Comment by sergiou87** [comment]
> It may actually fix it though. Is it possible for a session to be dealloc'ed if existing tasks associated with it are still in flight? If thats not possible, then this just might solve it. I need to look into some the cancel state today and verify those flows.

That's definitely a good point :smile: My knowledge about it is very scarce, but I don't see anything obvious that points in that direction, it seems like tasks can outlive sessions… but maybe I'm missing something :confused:

**Comment by kcharwood** [comment]
I think I'm going to move forward with #3152 for now. Thanks for digging in on this!

:beers:

**Comment by sergiou87** [comment]
Awesome! Nice work! And sorry I couldn't be of more help :sweat_smile:

**Pull request closed without merging**
