### PR TITLE
Adding missing nullability attributes

### PR DESCRIPTION
**Pull request by loudnate**

### CODE REVIEW

**Comment by kcharwood** [comment]
Thanks for the PR! What is your use case for nil success blocks?

**Comment by loudnate** [comment]
204 response codes, using a JSON response serializer.

**Comment by kcharwood** [comment]
@cnoon Didn't you just handle 204's in Alamofire? Anything we should be aware of here?

**Comment by loudnate** [comment]
Alternatively, we could route empty responses to the `failure:` case. Currently, though, this causes a crash when accessing the `responseObject` if the `AFHTTPSessionManager` classes are called from Swift and an empty response is received.

**Comment by kcharwood** [comment]
Yep makes sense. I've verified this with some simple test additions to the `AFHTTPSessionManager` class.

Would you be willing to retarget this PR to the 3_0_0 branch, and convert to `_Nullable`? I'd like to take those there!

**Comment by kcharwood** [comment]
You could also drop these tests into `AFHTTPSessionManagerTests` if you want:

```Objective-C
# pragma mark - Rest Interface

- (void)testThatSuccessBlockIsCalledFor200 {
    XCTestExpectation *expectation = [self expectationWithDescription:@"Request should succeed"];
    [self.manager
     GET:@"status/200"
     parameters:nil
     success:^(NSURLSessionDataTask * _Nonnull task, id  _Nonnull responseObject) {
         [expectation fulfill];
     }
     failure:nil];
    [self waitForExpectationsWithCommonTimeoutUsingHandler:nil];
}

- (void)testThatFailureBlockIsCalledFor404 {
    XCTestExpectation *expectation = [self expectationWithDescription:@"Request should succeed"];
    [self.manager
     GET:@"status/404"
     parameters:nil
     success:nil
     failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
         [expectation fulfill];
     }];
    [self waitForExpectationsWithCommonTimeoutUsingHandler:nil];
}

- (void)testThatResponseObjectIsEmptyFor204 {
    __block id urlResponseObject = nil;
    XCTestExpectation *expectation = [self expectationWithDescription:@"Request should succeed"];
    [self.manager
     GET:@"status/204"
     parameters:nil
     success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
         urlResponseObject = responseObject;
         [expectation fulfill];
     }
     failure:nil];
    [self waitForExpectationsWithCommonTimeoutUsingHandler:nil];
    XCTAssertNil(urlResponseObject);
}
```

**Comment by loudnate** [comment]
Done, thanks! Feel free to close this one, unless you'd like me to update it so these changes go to master too?

**Comment by kcharwood** [comment]
I'm going to close this one out and leave out of master. At this point, The 2.x branch is for critical features only. Since this only affects the NSURLSession API's, I'm going to leave it out for now.

Thanks again!

**Pull request closed without merging**
