### PR TITLE
Fixed crash in `AFURLRequestSerialization` if `stringByAddingPercentEncodingWithAllowedCharacters:` returned a nil string

### PR DESCRIPTION
**Pull request by liujianan901228**
fixed crash when  encoded = nil,  My App have this Crash sometimes, but i don't know how to it appearance.

### CODE REVIEW

**Comment by kcharwood** [comment]
Thanks for reporting this. Is there _anyway_ to get information around you reproduced the crash?

**Comment by kcharwood** [comment]
Also, could you please backmerge/rebase with master so we can get tests passing again on this branch before merging in?

Thanks!

**Comment by liujianan901228** [comment]
hi , beacuse i use github to fixed crash is first ,so i don't know how to do it and why has this warning:
Some checks haven’t completed yet
1 pending check
Details continuous-integration/travis-ci/pr — The Travis CI build is in progress
This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.

**Comment by kcharwood** [comment]
@liujianan901228 with no other reports of this crash, and no way to reproduce this crash, I'm going to leave this open as is for the time being.

Can you please:

- [ ] Define a reproducible case
- [ ] Create a test around the failure
- [ ] Decide what the fallback behavior should be (i.e. should we just append the substring directly?)

**Comment by tewha** [comment]
I think you've added this since so it can be closed, yes?

**Pull request closed without merging**
