### PR TITLE
Fixed image downloading cancellation race condition

### PR DESCRIPTION
**Pull request by kcharwood**
Addresses #3324

### CODE REVIEW

**Comment by florianschulz** [comment]
Thanks for addressing this issue that fast! 👍🏻

Unfortunately the unit test example I posted within the issue #3324 is wrong. The successCount should equal the number of requests. I also removed the image URLs from the test since they were fairly large downloads. The unit test now fails again, because now neither the failure block nor the success block get called anymore of the requests whose indices exceed the value in "maximumActiveDownloads". 

The fixed unit test:

```objc
- (void)testThatItCanDownloadAndCancelAndDownloadAgain {
    AFImageDownloader *downloader = [[AFImageDownloader alloc] initWithSessionManager:self.downloader.sessionManager
                                                               downloadPrioritization:self.downloader.downloadPrioritizaton
                                                               maximumActiveDownloads:1
                                                                           imageCache:self.downloader.imageCache];
    
    XCTestExpectation *expectation = [self expectationWithDescription:@"no download should fail"];
    __block NSUInteger successCount = 0;
    
    NSArray *imageURLRequests = @[self.pngRequest, self.jpegRequest];
    
    for (NSURLRequest *imageURLRequest in imageURLRequests) {
        AFImageDownloadReceipt *receipt = [downloader downloadImageForURLRequest:imageURLRequest success:nil failure:nil];
        [downloader cancelTaskForImageDownloadReceipt:receipt];
    }
    
    for (NSURLRequest *imageURLRequest in imageURLRequests) {
        [downloader downloadImageForURLRequest:imageURLRequest success:^(NSURLRequest * _Nonnull request, NSHTTPURLResponse * _Nullable response, UIImage * _Nonnull responseObject) {
            successCount++;
            if (successCount == [imageURLRequests count]) {
                [expectation fulfill];
            }
        } failure:^(NSURLRequest * _Nonnull request, NSHTTPURLResponse * _Nullable response, NSError * _Nonnull error) {
            [expectation fulfill];
        }];
    }
    
    [self waitForExpectationsWithCommonTimeoutUsingHandler:nil];
    
    XCTAssertTrue(successCount == [imageURLRequests count], @"all downloads should succeed");
}
```

**Comment by kcharwood** [comment]
You are right. I'll update that and then dig further.

The root of the issue here is cancelling a request and kicking it off again before the original one has a to chance to cancel, and only if that request to be cancelled is in the suspended state.

**Comment by kcharwood** [comment]
Thanks @florianschulz 

I've updated the unit test to be a bit better, and improved my patch. Let me know your thoughts.

**Comment by florianschulz** [comment]
Great job! It's working now for me. ✌️
Thanks again for addressing the issue so quickly. 

Just as a suggestion, I would still replace the image URLs in the test before merging it into master, since due to their download size, there is a chance of getting an expectation timeout under bad network conditions. It is also possible that the images will be removed from the server in the future. I couldn't find a good source for reliable image downloads, so I modified the test (as suggested above) to download only two images from httpbin and setting the maximumActiveDownloads to 1.

**Comment by kcharwood** [comment]
Thanks for the tip. Just switched over to gravatar.

**Comment by kcharwood** [comment]
Tests failed due to a certificate expiring. Need to get that one fixed first.

**Pull request merged**
